gui:
  scrollHeight: 10
  showCommandLog: false
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 3
  showBottomLine: false
  showFileTree: false
  nerdFontsVersion: '3'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editPreset: nvim
